apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ include "go-echo-example.fullname" . }}
  # labels and annotations are copied over to the
  # secret that will be created
  labels:
    {{- include "go-echo-example.labels" . | nindent 4 }}
  annotations: {}
spec:
  secretStoreRef:
    name: {{ include "go-echo-example.fullname" . }}
    kind: SecretStore
  refreshInterval: {{ .Values.externalSecret.refreshInterval}}
  target:
    # The secret name of the resource
    # Defaults to .metadata.name of the ExternalSecret
    # It is immutable
    # name: {{ include "go-echo-example.fullname" . }}

    # creationPolicy: 'Merge'
    creationPolicy: 'Owner'
    template:
      metadata:
        annotations: {}
        labels: {}
      # Use inline templates to construct your desired config file that contains your secret
      data:
        config.yaml: |
          {{`echo:
            prefix: "{{ (.config | fromJSON).echoPrefix }}"
          test: 1
          `}}
          
  data:
    - secretKey: config
      remoteRef:
        key: {{ .Values.externalSecret.secretKey}}