apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: {{ include "go-echo-example.fullname" . }}
spec:
  provider:
    aws:
      service: SecretsManager
      # service: ParameterStore
      region: {{ .Values.externalSecret.awsRegion }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ include "go-echo-example.serviceAccountName" . }}